name: Publish Package

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
      - "v[0-9]+.[0-9]+.[0-9]+-dev.[0-9]+"

jobs:
    a:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v6
        - name: A
          run: mkdir test
        - name: Build
          run: echo ${{ github.sha }} > test/Release.txt
        - name: Zip
          run: zip -r web-demo.zip test/Release.txt
        - name: Upload as artifact
          uses: actions/upload-artifact@v7
          with:
            path: web-demo.zip
            if-no-files-found: error
            archive: false

    b:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v6
        - name: A
          run: mkdir test
        - name: Build
          run: echo ${{ github.sha }} > test/Release2.txt
        - name: Upload as artifact
          uses: actions/upload-artifact@v7
          with:
            path: test/Release2.txt
            if-no-files-found: error
            archive: false
            
    build:
      runs-on: ubuntu-latest
      needs: [a, b]
      permissions:
        contents: write
      steps:
        - name: Download
          uses: actions/download-artifact@v8
          with:
            path: artifacts/
            merge-multiple: true
            skip-decompress: true
        - uses: actions/attest@v4
          with:
            subject-path: artifacts/*.*
        - name: Release
          uses: ncipollo/release-action@389305c50bc7406ce7e55077eb8b863e0f0a3083
          with:
            artifacts: artifacts/*.*
            prerelease: ${{contains(github.ref_name, '-dev')}}
            generateReleaseNotes: true
            immutableCreate: true
